vich_uploader:
    db_driver: orm

    mappings:
       albums:
           uri_prefix: /images/albums
           upload_destination: '%kernel.project_dir%/public/images/albums'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
